project:
  type: website
  output-dir: docs

website:
  title: "Zuzanna Wasiluk"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - olaf_economics.qmd
      - mini_project_a.qmd
      - mini_project_b.qmd
      - mini_project_c.qmd

format:
  html:
    theme: style.scss 
    toc: true
    page-layout: full